version: "3.7"

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    image: ecommerce-app-server-image
    container_name: ecommerce-app-server
    command: node index.js
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3002:3002"
    env_file: ./.env
    environment:
      - NODE_ENV=development

volumes:
  web-root:
    driver: local
